spring:
  application:
   name: GATEWAY-SERVICE  
   gateway:
     discovery:
       locator:
         enabled: true
     httpclient:
       connectTimeout: 10000
       responseTimeout: 1000
   routes:
     - id: USER-SERVICE
       uri: lb://USER-SERVICE
       predicates:
       - Path=/users/**
     - id: PRODUCT
       uri: lb://PRODUCT
       predicates:
       - Path=/product/**  
     - id: FALLBACK
       uri: forward:/fallback
       predicates:
       - Path=/product/**, /users/** 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
      hostname: localhost "